config/routes.rb
Rails.application.routes.draw do


  resources :guides, only: [:index]

  resources :shipments do
    resources :guides, module: :shipment do
      collection do
        get :report
        post :import
      end
    end
  end

  devise_for :users

  authenticated :user do
    root 'shipments#index', as: :authenticated_root
  end

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guide.rb
class Guide < ApplicationRecord
  belongs_to :shipment
  before_save :dest, :if => :new_record?

  def dest
    self.destinatario="#{self.radicado}- #{self.destinatario}"
  end


end

app/models/shipment.rb
class Shipment < ApplicationRecord
  has_many :guides, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  def index
    if params[:q]
      @guides=Guide.where("lower(radicado) like :q", q: "%#{params[:q].downcase}%")     
       
    else
      @guides=Guide.none
    end
  end
end

app/controllers/shipment/guides_controller.rb
#encoding: utf-8
class Shipment::GuidesController < ApplicationController
  respond_to :html, :xlsx
  before_action :set_shipment
  before_action :set_guide, only: [:destroy]
  require 'csv'

  def report

    @guides=@shipment.guides
    render xlsx: 'report',filename: "envios#{Date.current}.xlsx"    

  end

  def index
  end

  def show
  end

  def new
    @guide=@shipment.guides.new
  end

  def create
    @guide=@shipment.guides.new(guide_params)
    if @guide.save
      flash[:success] = "Guía registrada"
      respond_with @shipment
    else
      flash[:alert] = "Problemas con el registro"
      render :new
    end
  end

  def destroy
    @guide.destroy
    flash[:success] = "Guía eliminada correctamente"
    respond_with @shipment
  end

  def import
    puts "Registrar la importación"
    begin
      import_file=params[:guides][:import_file]

      archivo=File.open(import_file.path, "r")
      csv_string = archivo.read.encode!("UTF-8", "iso-8859-1", invalid: :replace)

      CSV.parse(csv_string, col_sep: ";", headers: true, encoding: "iso-8859-1:UTF-8") do |row|
        valor=row[1]
        guia=row[0]
        radicado=valor.split("-")[0]
        envio=Guide.where(radicado: radicado).first
        unless envio.nil?
          envio.update(guia: guia)         
        end
      end 

      flash[:success] = "Guias cargadas correctamente"

      redirect_to shipment_path(@shipment)

    rescue => exception 
      flash[:error] = "Problemas para cargar guias"
      p exception
      redirect_to shipment_path(@shipment)
    end
  end

  private

  def set_shipment
    @shipment=Shipment.find(params[:shipment_id])
  end  

  def set_guide
    @guide=@shipment.guides.find(params[:id])
  end

  def guide_params
    params.require(:guide).permit(:destinatario, :direccion, :ciudad, :peso, :observaciones, :radicado)
  end
end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
  before_action :set_shipment, only: [:show, :edit, :update, :destroy]

  # GET /shipments
  # GET /shipments.json
  def index
    @shipments = Shipment.all
  end

  # GET /shipments/1
  # GET /shipments/1.json
  def show
    @guides=@shipment.guides
  end

  # GET /shipments/new
  def new
    @shipment = Shipment.new
  end

  # GET /shipments/1/edit
  def edit
  end

  # POST /shipments
  # POST /shipments.json
  def create
    @shipment = Shipment.new(shipment_params)

    respond_to do |format|
      if @shipment.save
        format.html { redirect_to @shipment, notice: 'Shipment was successfully created.' }
        format.json { render :show, status: :created, location: @shipment }
      else
        format.html { render :new }
        format.json { render json: @shipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shipments/1
  # PATCH/PUT /shipments/1.json
  def update
    respond_to do |format|
      if @shipment.update(shipment_params)
        format.html { redirect_to @shipment, notice: 'Shipment was successfully updated.' }
        format.json { render :show, status: :ok, location: @shipment }
      else
        format.html { render :edit }
        format.json { render json: @shipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shipments/1
  # DELETE /shipments/1.json
  def destroy
    @shipment.destroy
    respond_to do |format|
      format.html { redirect_to shipments_url, notice: 'Shipment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shipment
      @shipment = Shipment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shipment_params
      params.require(:shipment).permit(:fecha_envio_at, :comments)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def dashboard
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/helpers/shipment/guides_helper.rb
module Shipment::GuidesHelper
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/guides/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th>Nº Envio</th>
                  <th>Guía</th>                  
                  <th>Radicado</th>
                  <th>Destinatario</th>
                  <th>Dirección</th>
                  <th>Ciudad</th>                  
                </tr>
              </thead>
              <tbody>
                <% @guides.each do |guide| %>
                  <tr>
                    <td><%= guide.shipment.id %></td>
                    <td><%= guide.guia %></td>
                    <td><%= guide.radicado %></td>
                    <td><%= guide.destinatario %></td>
                    <td><%= guide.direccion %></td>
                    <td><%= guide.ciudad %></td>
                  </tr>                  
                <% end %>
              </tbody>
            </table>     
        <% if @guides.empty? %>
          <h3>Radicado no encontrado</h3>     
        <% end %>   
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">CRA</a>
    </div>

    <% if user_signed_in? %>
      <form class="navbar-form navbar-left" action="<%= guides_path %>">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="radicado" name="q" value="<%= params[:q] %>">
        </div>
        <button type="submit" class="btn btn-default">Buscar</button>
      </form>    
      
    <% end %>


    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
        <!-- <li><a href="#">Link</a></li> -->
<!--         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Envios <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
 -->        
      </ul>      
      <% if user_signed_in? %>
        <%= link_to "cerrar session",destroy_user_session_path, method: :delete, class: "btn btn-success navbar-btn navbar-right"  %>
      <% else %>
        <%= link_to "Entrar", new_user_session_path, class: "btn btn-success navbar-btn navbar-right"  %>        
      <% end %>

    </div><!--/.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cra</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">  

  <%= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css") %>  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
 <div id="wrapper" class="<%= params[:controller] %>.<%= params[:action] %>">

      <% unless flash.empty? %>
        <script type="text/javascript">
              toastr.options = {
                  closeButton: true,
                  progressBar: true,
                  showMethod: 'slideDown',
                  timeOut: 4000,
                  preventDuplicates: false
              };
            <% flash.each do |f| %>
            <% 
              type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info')
            %>
               toastr['<%= type %>']('<%= f[1] %>');
            <% end %>
        </script>
       <% end %>  
       
  <%= yield %>   
 </div>

</body>
</html>

app/views/shipment/guides/_form.html.erb
<%= form_for([@shipment, @guide], role: "form") do |f| %>
  <% if @guide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guide.errors.count, "error") %> prohibited this shipment from being saved:</h2>

      <ul>
      <% @guide.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :radicado %>
    <%= f.text_field :radicado, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :destinatario %>
    <%= f.text_field :destinatario, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :direccion %>
    <%= f.text_field :direccion, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :ciudad %>
    <%= f.text_field :ciudad, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :peso %>
    <%= f.text_field :peso, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :observaciones %>
    <%= f.text_area :observaciones, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/shipment/guides/index.html.erb
<h1>Shipment::Guides#index</h1>
<p>Find me in app/views/shipment/guides/index.html.erb</p>

app/views/shipment/guides/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <%= render 'form' %>      
    </div>
  </div>
</div>

app/views/shipment/guides/show.html.erb
<h1>Shipment::Guides#show</h1>
<p>Find me in app/views/shipment/guides/show.html.erb</p>

app/views/shipments/_form.html.erb
<%= form_for(shipment, role: "form") do |f| %>
  <% if shipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shipment.errors.count, "error") %> prohibited this shipment from being saved:</h2>

      <ul>
      <% shipment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :fecha_envio_at %>
    <%= f.date_select :fecha_envio_at, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :comments %>
    <%= f.text_area :comments, class: "form-control" %>
  </div>

  <div class="acform-group">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/shipments/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1>Editar envio</h1>

      <%= render 'form', shipment: @shipment %>
      <hr>
      <%= link_to 'Ver', @shipment %> |
      <%= link_to 'Regresar', shipments_path %>
      
    </div>
  </div>
</div>

app/views/shipments/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">

      <h1>Envios</h1>

      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Fecha envio at</th>
            <th>Comments</th>
            <th colspan="3">Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @shipments.each do |shipment| %>
            <tr>
              <td><%= shipment.fecha_envio_at %></td>
              <td><%= shipment.comments %></td>
              <td><%= link_to 'Ver', shipment %></td>
              <td><%= link_to 'Editar', edit_shipment_path(shipment) %></td>
              <td><%= link_to 'Borrar', shipment, method: :delete, data: {  confirm: '¿Esta usted seguro?', mensaje: 'El envio se borrara definitivamente ' },class: "btn btn-danger btn-xs" %></td>
              <td>

            </tr>
          <% end %>
        </tbody>
      </table>


      <br>

      <%= link_to 'Nuevo envio', new_shipment_path %>
      
    </div>
  </div>
</div>

app/views/shipments/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1>Nuevo envio</h1>

      <%= render 'form', shipment: @shipment %>
      <br>
      <%= link_to 'Regresar', shipments_path, class: "btn btn-default" %>
      
    </div>
  </div>
</div>

app/views/shipments/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="well">
        <p>
          <strong>Fecha envio:</strong>
          <%= @shipment.fecha_envio_at %>
        </p>

        <p>
          <strong>Comentarios:</strong>
          <%= @shipment.comments %>
        </p>
        
      </div>
        
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Cargar archivo de guías</h3>
          </div>
          <div class="panel-body">
            <%= form_for :guides, url: import_shipment_guides_path(@shipment), html: { multipart: true } do |f| %>

              <%= f.file_field :import_file %>
              <br>
              <%= f.submit class: "btn btn-default" %>
            <% end %>
          </div>
        </div>


        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>Guía</th>      
              <th>Destinatario</th>
              <th>Dirección</th>
              <th>Radicado</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            <% @guides.each do |guide| %>
              <tr>
                <td><%= guide.guia %></td>
                <td><%= guide.destinatario %></td>  
                <td><%= guide.direccion %></td>
                <td><%= guide.radicado %></td>
                <td><%= link_to 'Borrar', shipment_guide_path(@shipment, guide), method: :delete, data: {  confirm: '¿Esta usted seguro?', mensaje: 'La guía se borrara definitivamente ' },class: "btn btn-danger btn-xs" %></td>
                <td>
                  
                </td>
              </tr>    
            <% end %>
          </tbody>
        </table>  


        <hr>

        <%= link_to "Registrar guia", new_shipment_guide_path(@shipment)  %> |
        <%= link_to 'Editar envio', edit_shipment_path(@shipment) %> |
        <%= link_to 'Regresar', shipments_path %> |

        <%= link_to "Generar excel", report_shipment_guides_path(@shipment,format: 'xlsx' ) %>

      
    </div>
  </div>
</div>

app/views/welcome/dashboard.html.erb
esta es la dashboard del usuario

app/views/welcome/index.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">CRA</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <%= link_to "Entrar", new_user_session_path, class: "btn btn-success navbar-btn navbar-right"  %>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

 <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>Bienvenido a mensajeria CRA</h1>
        <p>Sistema para el manejo de la mensajeria de la corporación Regional Autonoma</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; 2016 Henry Guzmán <a href="https://twitter.com/hguzman10">@hguzman10</a></p>
      </footer>
    </div> <!-- /container -->